#!/bin/sh
# loc.sh installer — interactively generates ./loc.sh in the current directory.
# Usage: curl -fsSL https://github.com/arturcarvalho/loc.sh/raw/main/install.sh | sh
set -eu

OUT="./loc.sh"
FORCE=0
for arg in "$@"; do
  case "$arg" in
    --force|-f) FORCE=1 ;;
    -h|--help)
      cat <<'HELP'
Usage: install.sh [--force]
  Interactively generates ./loc.sh that counts lines of code in this
  directory via cloc. You are asked which file categories to exclude.
HELP
      exit 0 ;;
    *)
      printf "Unknown argument: %s\n" "$arg" >&2
      exit 2 ;;
  esac
done

if [ -e "$OUT" ] && [ "$FORCE" -eq 0 ]; then
  printf "%s already exists. Re-run installer with --force to overwrite.\n" "$OUT" >&2
  exit 1
fi

# Open fd 3 to the terminal for prompts. Do NOT swap fd 0 — under `curl | sh`
# fd 0 is the pipe carrying the script and the parser is still streaming it.
if ! { exec 3<>/dev/tty; } 2>/dev/null; then
  printf "install.sh needs an interactive terminal for prompts.\n" >&2
  exit 1
fi

ask() {
  printf "%s [Y/n]: " "$1" >&3
  REPLY=""
  read -r REPLY <&3 || REPLY=""
  case "$REPLY" in
    n|N|no|NO|No) return 1 ;;
    *) return 0 ;;
  esac
}

ask_no() {
  printf "%s [y/N]: " "$1" >&3
  REPLY=""
  read -r REPLY <&3 || REPLY=""
  case "$REPLY" in
    y|Y|yes|YES|Yes) return 0 ;;
    *) return 1 ;;
  esac
}

cat >&3 <<'INTRO'
loc.sh installer — generates ./loc.sh in the current directory.

Categories you can exclude (default = exclude, Enter to confirm):
  - Markdown files     (.md)
  - JSON files         (.json, .json5)
  - Config files       (YAML, TOML, INI)
  - Media / binary     (images, audio, video, fonts, archives, pdf)
  - Lock files         (package-lock.json, yarn.lock, Cargo.lock, ...)
  - Shell scripts      (.sh, .bash, .zsh, .ksh)

After the categories you'll be asked about each top-level folder
(default = keep).

INTRO

EXCLUDE_LANGS=""
EXCLUDE_EXTS=""
NOT_MATCH_F=""
EXCLUDE_DIRS=""

add_lang() {
  if [ -z "$EXCLUDE_LANGS" ]; then
    EXCLUDE_LANGS="$1"
  else
    EXCLUDE_LANGS="$EXCLUDE_LANGS,$1"
  fi
}

add_dir() {
  if [ -z "$EXCLUDE_DIRS" ]; then
    EXCLUDE_DIRS="$1"
  else
    EXCLUDE_DIRS="$EXCLUDE_DIRS,$1"
  fi
}

if ask "Exclude Markdown?";                     then add_lang "Markdown"; fi
if ask "Exclude JSON?";                         then add_lang "JSON,JSON5"; fi
if ask "Exclude config files (YAML/TOML/INI)?"; then add_lang "YAML,TOML,INI"; fi
if ask "Exclude media/binary assets?";          then EXCLUDE_EXTS="png,jpg,jpeg,gif,svg,ico,webp,bmp,tiff,mp4,mov,mp3,wav,ogg,flac,m4a,pdf,woff,woff2,ttf,eot,otf,zip,gz,tar,7z,rar"; fi
if ask "Exclude lock files?";                   then NOT_MATCH_F='package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|Gemfile\.lock|poetry\.lock|composer\.lock|go\.sum'; fi
if ask "Exclude shell scripts?";                then add_lang "Bourne Shell,Bourne Again Shell,Korn Shell,zsh"; fi

# Top-level folders: ask y/N per folder (default N — keep). Always-skipped
# folders (.git) are not listed; the always-skipped non-git noise list is
# applied automatically at run time.
LISTED_DIRS=""
for d in * .*; do
  [ -d "$d" ] || continue
  case "$d" in .|..|.git) continue ;; esac
  LISTED_DIRS="${LISTED_DIRS}${LISTED_DIRS:+ }$d"
done
if [ -n "$LISTED_DIRS" ]; then
  printf "\nTop-level folders (press Enter to keep each):\n" >&3
  for d in $LISTED_DIRS; do
    if ask_no "  Exclude $d/?"; then
      add_dir "$d"
    fi
  done
fi

# Emit ./loc.sh — first heredoc expands baked-in values, second is literal.
cat > "$OUT" <<EOF
#!/usr/bin/env bash
# Generated by loc.sh installer (https://github.com/arturcarvalho/loc.sh).
# Counts lines of code in the current directory via cloc.
EXCLUDE_LANGS='${EXCLUDE_LANGS}'
EXCLUDE_EXTS='${EXCLUDE_EXTS}'
NOT_MATCH_F='${NOT_MATCH_F}'
EXCLUDE_DIRS='${EXCLUDE_DIRS}'
EOF

cat >> "$OUT" <<'EOF'

set -euo pipefail

if ! command -v cloc >/dev/null 2>&1; then
  printf "loc.sh needs 'cloc' but it is not installed.\nInstall on macOS: brew install cloc\n" >&2
  exit 127
fi

ARGS=()
[ -n "$EXCLUDE_LANGS" ] && ARGS+=("--exclude-lang=$EXCLUDE_LANGS")
[ -n "$EXCLUDE_EXTS"  ] && ARGS+=("--exclude-ext=$EXCLUDE_EXTS")

# Always self-exclude this script; merge in any user-chosen lock-file pattern.
SKIP_BASENAMES='loc\.sh'
[ -n "$NOT_MATCH_F" ] && SKIP_BASENAMES="$SKIP_BASENAMES|$NOT_MATCH_F"

if git rev-parse --git-dir >/dev/null 2>&1; then
  # Tracked + untracked-not-ignored files (so uncommitted work is counted but
  # .gitignore is respected). cloc's --not-match-f is ignored under
  # --list-file, so filter via grep instead.
  if [ -n "$EXCLUDE_DIRS" ]; then
    DIR_PATTERN=$(printf '%s' "$EXCLUDE_DIRS" | sed 's/\./\\./g; s/,/|/g')
    exec cloc "${ARGS[@]}" --list-file=<(
      git ls-files -co --exclude-standard \
        | grep -Ev "(^|/)($SKIP_BASENAMES)\$" \
        | grep -Ev "(^|/)($DIR_PATTERN)/"
    )
  else
    exec cloc "${ARGS[@]}" --list-file=<(
      git ls-files -co --exclude-standard | grep -Ev "(^|/)($SKIP_BASENAMES)\$"
    )
  fi
else
  ALL_EXCLUDE_DIRS="node_modules,vendor,dist,build,target,.venv,venv,.next,.nuxt,.cache,coverage,.git"
  [ -n "$EXCLUDE_DIRS" ] && ALL_EXCLUDE_DIRS="$ALL_EXCLUDE_DIRS,$EXCLUDE_DIRS"
  ARGS+=("--not-match-f=^($SKIP_BASENAMES)$")
  ARGS+=("--exclude-dir=$ALL_EXCLUDE_DIRS")
  exec cloc "${ARGS[@]}" .
fi
EOF

chmod +x "$OUT"
printf "\nCreated %s — run it with: ./loc.sh\n" "$OUT"
